from __future__ import annotations

import math
import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Optional, Tuple

from rdkit import Chem, DataStructs
from rdkit.Chem import Draw, rdDepictor, rdFingerprintGenerator
from rdkit.Chem.Scaffolds import MurckoScaffold


FINGERPRINT_GENERATOR = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)


@dataclass
class SarCompound:
    id: int
    name: Optional[str]
    smiles: str
    potency: float
    mol: Chem.Mol
    scaffold: str
    r_groups: Dict[str, str]
    properties: Dict[str, Any]


def generate_sar_summary(
    molecules: List[Dict[str, Any]],
    potency_column: str,
    potency_direction: str = "lower_is_better",
    admet_columns: Optional[List[str]] = None,
    min_fold_change: float = 3.0,
) -> Dict[str, Any]:
    admet_columns = admet_columns or []
    if potency_direction not in {"lower_is_better", "higher_is_better"}:
        raise ValueError("potency_direction must be lower_is_better or higher_is_better.")
    if min_fold_change <= 1:
        raise ValueError("min_fold_change must be greater than 1.")

    compounds = _prepare_compounds(molecules, potency_column)
    scaffold_groups = _group_by_scaffold(compounds)
    pair_rows = _find_matched_pair_evidence(scaffold_groups, potency_direction, min_fold_change, admet_columns)
    pair_rows.sort(key=lambda row: row["fold_change"], reverse=True)

    trend_counter: Counter[Tuple[Optional[str], str, str]] = Counter()
    risk_counter: Counter[Tuple[Optional[str], str, str]] = Counter()
    promising_counter: Counter[Optional[str]] = Counter()
    scaffold_counter: Counter[str] = Counter()

    for row in pair_rows:
        key = (row["position"], row["weaker_substitution"], row["stronger_substitution"])
        trend_counter[key] += 1
        promising_counter[row["position"]] += 1
        scaffold_counter[row["scaffold"]] += 1
        if "ADMET risk" in row["note"]:
            risk_counter[key] += 1

    key_trends = _summarize_trends(trend_counter, scaffold_counter, pair_rows)
    risky_modifications = _summarize_risks(risk_counter, pair_rows)
    promising_positions = _summarize_positions(promising_counter)
    suggested_analogs = _suggest_next_analogs(trend_counter, promising_counter)
    scaffold_map = _build_scaffold_map(scaffold_groups, pair_rows)

    return {
        "potency_column": potency_column,
        "potency_direction": potency_direction,
        "compound_count": len(molecules),
        "analyzable_compound_count": len(compounds),
        "scaffold_count": len(scaffold_groups),
        "matched_pair_count": len(pair_rows),
        "key_sar_trends": key_trends,
        "risky_modifications": risky_modifications,
        "promising_positions": promising_positions,
        "suggested_next_analogs": suggested_analogs,
        "evidence_table": pair_rows[:50],
        "scaffold_groups": {scaffold: [compound.id for compound in members] for scaffold, members in scaffold_groups.items()},
        "scaffold_map": scaffold_map,
        "admet_columns": admet_columns,
        "metadata": {
            "min_fold_change": min_fold_change,
            "method": "Bemis-Murcko scaffold grouping plus same-scaffold single-position R-group changes.",
            "limitations": (
                "Matched molecular pairs are heuristic. R-groups are generated by removing the "
                "Bemis-Murcko scaffold when possible; macrocycles, disconnected structures, or "
                "large core changes may not yield position-specific evidence."
            ),
        },
    }


def _prepare_compounds(molecules: List[Dict[str, Any]], potency_column: str) -> List[SarCompound]:
    compounds: List[SarCompound] = []
    for molecule in molecules:
        potency = _parse_number(_property_value(molecule, potency_column))
        mol = Chem.MolFromSmiles(molecule.get("smiles", ""))
        if potency is None or mol is None:
            continue

        scaffold_mol = MurckoScaffold.GetScaffoldForMol(mol)
        if scaffold_mol.GetNumAtoms() == 0:
            scaffold = Chem.MolToSmiles(mol, canonical=True)
            core = mol
        else:
            scaffold = Chem.MolToSmiles(scaffold_mol, canonical=True)
            core = scaffold_mol

        compounds.append(
            SarCompound(
                id=int(molecule["id"]),
                name=molecule.get("name"),
                smiles=molecule["smiles"],
                potency=potency,
                mol=mol,
                scaffold=scaffold,
                r_groups=_r_groups_for_core(mol, core),
                properties=molecule.get("properties", {}),
            )
        )
    return compounds


def _group_by_scaffold(compounds: Iterable[SarCompound]) -> Dict[str, List[SarCompound]]:
    groups: Dict[str, List[SarCompound]] = defaultdict(list)
    for compound in compounds:
        groups[compound.scaffold].append(compound)
    return dict(groups)


def _find_matched_pair_evidence(
    scaffold_groups: Dict[str, List[SarCompound]],
    potency_direction: str,
    min_fold_change: float,
    admet_columns: List[str],
) -> List[Dict[str, Any]]:
    evidence: List[Dict[str, Any]] = []

    for scaffold, compounds in scaffold_groups.items():
        if len(compounds) < 2:
            continue
        fingerprints = {compound.id: FINGERPRINT_GENERATOR.GetFingerprint(compound.mol) for compound in compounds}

        for left_index, left in enumerate(compounds):
            for right in compounds[left_index + 1 :]:
                weaker, stronger, fold_change = _rank_pair(left, right, potency_direction)
                if fold_change < min_fold_change:
                    continue

                difference = _single_position_difference(weaker.r_groups, stronger.r_groups)
                if difference is None:
                    similarity = DataStructs.TanimotoSimilarity(fingerprints[left.id], fingerprints[right.id])
                    if similarity < 0.45:
                        continue
                    position, weaker_substitution, stronger_substitution = None, "multi-site or core-adjacent change", "multi-site or core-adjacent change"
                else:
                    position, weaker_substitution, stronger_substitution = difference

                admet_note = _admet_note(weaker, stronger, admet_columns)
                note = f"{fold_change:.1f}x potency improvement"
                if admet_note:
                    note = f"{note}; ADMET risk: {admet_note}"

                evidence.append(
                    {
                        "scaffold": scaffold,
                        "weaker_compound_id": weaker.id,
                        "stronger_compound_id": stronger.id,
                        "weaker_name": weaker.name,
                        "stronger_name": stronger.name,
                        "weaker_potency": weaker.potency,
                        "stronger_potency": stronger.potency,
                        "fold_change": round(fold_change, 3),
                        "position": position,
                        "weaker_substitution": weaker_substitution,
                        "stronger_substitution": stronger_substitution,
                        "note": note,
                    }
                )

    return evidence


def _rank_pair(left: SarCompound, right: SarCompound, potency_direction: str) -> Tuple[SarCompound, SarCompound, float]:
    if potency_direction == "lower_is_better":
        stronger, weaker = (left, right) if left.potency < right.potency else (right, left)
        fold_change = weaker.potency / stronger.potency if stronger.potency else math.inf
    else:
        stronger, weaker = (left, right) if left.potency > right.potency else (right, left)
        fold_change = stronger.potency / weaker.potency if weaker.potency else math.inf
    return weaker, stronger, fold_change


def _r_groups_for_core(mol: Chem.Mol, core: Chem.Mol) -> Dict[str, str]:
    try:
        sidechain_mol = Chem.ReplaceCore(mol, core, labelByIndex=True)
    except Exception:
        return {}
    if sidechain_mol is None:
        return {"core": "H"}

    groups: Dict[str, List[str]] = defaultdict(list)
    for fragment in Chem.GetMolFrags(sidechain_mol, asMols=True, sanitizeFrags=True):
        smiles = Chem.MolToSmiles(fragment, canonical=True)
        labels = re.findall(r"\[(\d+)\*\]", smiles)
        label = f"R{int(labels[0]) + 1}" if labels else "R?"
        cleaned = re.sub(r"\[\d+\*\]", "[*]", smiles)
        groups[label].append(cleaned)
    return {label: ".".join(sorted(values)) for label, values in groups.items()} or {"core": "H"}


def _single_position_difference(
    weaker_groups: Dict[str, str],
    stronger_groups: Dict[str, str],
) -> Optional[Tuple[Optional[str], str, str]]:
    positions = sorted(set(weaker_groups) | set(stronger_groups))
    differences = [
        (position, weaker_groups.get(position, "H"), stronger_groups.get(position, "H"))
        for position in positions
        if weaker_groups.get(position, "H") != stronger_groups.get(position, "H")
    ]
    if len(differences) != 1:
        return None
    return differences[0]


def _property_value(molecule: Dict[str, Any], column: str) -> Any:
    properties = molecule.get("properties", {})
    if column in properties:
        return properties[column]
    lowered = {str(key).lower(): value for key, value in properties.items()}
    return lowered.get(column.lower())


def _parse_number(value: Any) -> Optional[float]:
    if value is None:
        return None
    if isinstance(value, (int, float)):
        if math.isnan(value):
            return None
        return float(value)
    match = re.search(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", str(value).replace(",", ""))
    return float(match.group(0)) if match else None


def _admet_note(weaker: SarCompound, stronger: SarCompound, admet_columns: List[str]) -> str:
    notes: List[str] = []
    for column in admet_columns:
        weaker_value = _parse_number(_property_value({"properties": weaker.properties}, column))
        stronger_value = _parse_number(_property_value({"properties": stronger.properties}, column))
        if weaker_value is None or stronger_value is None:
            continue
        delta = stronger_value - weaker_value
        if abs(delta) < 1e-9:
            continue
        direction = "increased" if delta > 0 else "decreased"
        notes.append(f"{column} {direction} from {weaker_value:g} to {stronger_value:g}")
    return "; ".join(notes)


def _summarize_trends(
    trend_counter: Counter[Tuple[Optional[str], str, str]],
    scaffold_counter: Counter[str],
    evidence: List[Dict[str, Any]],
) -> List[str]:
    if not evidence:
        return ["No potency-associated matched-pair trends met the requested fold-change threshold."]

    trends = []
    for (position, weaker_sub, stronger_sub), count in trend_counter.most_common(6):
        position_label = position or "a multi-site/core-adjacent region"
        best_fold = max(
            row["fold_change"]
            for row in evidence
            if row["position"] == position and row["weaker_substitution"] == weaker_sub and row["stronger_substitution"] == stronger_sub
        )
        trends.append(
            f"{weaker_sub} -> {stronger_sub} at {position_label} is associated with potency gains "
            f"in {count} matched pair(s), up to {best_fold:.1f}x."
        )

    top_scaffold, scaffold_hits = scaffold_counter.most_common(1)[0]
    trends.append(f"The scaffold {top_scaffold} contributes the most SAR evidence ({scaffold_hits} improving pair(s)).")
    return trends


def _summarize_risks(
    risk_counter: Counter[Tuple[Optional[str], str, str]],
    evidence: List[Dict[str, Any]],
) -> List[str]:
    risks = []
    for (position, weaker_sub, stronger_sub), count in risk_counter.most_common(5):
        position_label = position or "multi-site/core-adjacent region"
        risks.append(
            f"{weaker_sub} -> {stronger_sub} at {position_label} improves potency but shifts tracked ADMET values in {count} pair(s)."
        )
    if risks:
        return risks

    if evidence:
        return ["No ADMET-linked risky modifications were detected from the supplied optional columns."]
    return ["Insufficient matched-pair evidence to identify risky modifications."]


def _summarize_positions(promising_counter: Counter[Optional[str]]) -> List[str]:
    if not promising_counter:
        return ["No single-position substitutions met the evidence threshold."]
    return [
        f"{position or 'multi-site/core-adjacent region'} appears promising based on {count} improving pair(s)."
        for position, count in promising_counter.most_common(5)
    ]


def _suggest_next_analogs(
    trend_counter: Counter[Tuple[Optional[str], str, str]],
    promising_counter: Counter[Optional[str]],
) -> List[str]:
    suggestions = []
    for (position, _, stronger_sub), _ in trend_counter.most_common(5):
        position_label = position or "the same modified region"
        suggestions.append(f"Prepare analogs retaining {stronger_sub} at {position_label} while scanning nearby size/electronics.")
    for position, _ in promising_counter.most_common(3):
        position_label = position or "the multi-site/core-adjacent region"
        suggestions.append(f"Design a focused mini-series at {position_label} with matched potency and ADMET readouts.")
    return suggestions[:6] or ["Add more same-scaffold compounds with measured potency to enable next-analog suggestions."]


def _build_scaffold_map(scaffold_groups: Dict[str, List[SarCompound]], evidence: List[Dict[str, Any]]) -> Dict[str, Any]:
    if not scaffold_groups:
        return {"scaffold_smiles": None, "scaffold_svg": "", "vectors": []}

    if evidence:
        scaffold = Counter(row["scaffold"] for row in evidence).most_common(1)[0][0]
    else:
        scaffold = max(scaffold_groups, key=lambda key: len(scaffold_groups[key]))

    core = Chem.MolFromSmiles(scaffold)
    if core is None:
        return {"scaffold_smiles": scaffold, "scaffold_svg": "", "vectors": []}

    core = Chem.Mol(core)
    rdDepictor.Compute2DCoords(core)
    width, height = 520, 320
    drawer = Draw.MolDraw2DSVG(width, height)
    drawer.DrawMolecule(core)
    atom_points = {
        atom_index: drawer.GetDrawCoords(atom_index)
        for atom_index in range(core.GetNumAtoms())
    }
    drawer.FinishDrawing()
    scaffold_svg = re.sub(r"^<\?xml[^>]*>\s*", "", drawer.GetDrawingText())

    vector_atom_indices = _scaffold_vector_atom_indices(core, scaffold_groups.get(scaffold, []))
    center_x = sum(point.x for point in atom_points.values()) / max(len(atom_points), 1)
    center_y = sum(point.y for point in atom_points.values()) / max(len(atom_points), 1)
    vectors = []
    for atom_index in sorted(vector_atom_indices):
        point = atom_points[atom_index]
        dx = point.x - center_x
        dy = point.y - center_y
        length = math.hypot(dx, dy) or 1.0
        label_x = _clamp(point.x + (dx / length) * 46, 26, width - 26)
        label_y = _clamp(point.y + (dy / length) * 46, 26, height - 26)
        vectors.append(
            {
                "label": f"R{atom_index + 1}",
                "atom_index": atom_index,
                "x": round(point.x / width * 100, 2),
                "y": round(point.y / height * 100, 2),
                "label_x": round(label_x / width * 100, 2),
                "label_y": round(label_y / height * 100, 2),
            }
        )

    return {
        "scaffold_smiles": scaffold,
        "scaffold_svg": scaffold_svg,
        "vectors": vectors,
    }


def _scaffold_vector_atom_indices(core: Chem.Mol, compounds: List[SarCompound]) -> set[int]:
    vector_atom_indices: set[int] = set()
    for compound in compounds:
        match = compound.mol.GetSubstructMatch(core)
        if not match:
            continue
        matched_atoms = set(match)
        mol_to_core = {mol_atom_index: core_atom_index for core_atom_index, mol_atom_index in enumerate(match)}
        for mol_atom_index, core_atom_index in mol_to_core.items():
            atom = compound.mol.GetAtomWithIdx(mol_atom_index)
            if any(neighbor.GetIdx() not in matched_atoms for neighbor in atom.GetNeighbors()):
                vector_atom_indices.add(core_atom_index)
    return vector_atom_indices


def _clamp(value: float, minimum: float, maximum: float) -> float:
    return max(minimum, min(maximum, value))
